FROM node:24-alpine AS builder

ARG WITH_OTEL

WORKDIR /builder

COPY ./package.json ./package-lock.json ./

RUN npm ci

COPY ./src/ ./src/

RUN npm run build && npm install --omit=dev --omit=optional ${WITH_OTEL:+--include=optional}

FROM tyrrrz/discordchatexporter:2.47.1

ARG WITH_OTEL

LABEL \
  org.opencontainers.image.source=https://github.com/yellow-corps/ibis \
  org.opencontainers.image.description="ibis discord chat exporter${WITH_OTEL:+ with otel}" \
  org.opencontainers.image.licenses=MIT

ENV WITH_OTEL=$WITH_OTEL

RUN \
  apk add --no-cache "nodejs=~24" && \
  addgroup -S exporter && \
  adduser -S exporter -G exporter

USER exporter
WORKDIR /home/exporter

COPY --from=builder /builder/target/index.mjs ./
COPY --from=builder /builder/node_modules ./node_modules
COPY ./docker-entrypoint.sh ./docker-entrypoint.sh

STOPSIGNAL SIGKILL
ENTRYPOINT ["/bin/sh", "-c", "./docker-entrypoint.sh"]
