name: ibis

services:
  discord:
    container_name: discord
    image: ghcr.io/yellow-corps/ibis-discord:latest
    build:
      context: ./discord
      dockerfile: ./Containerfile
    restart: unless-stopped
    environment:
      RED_TOKEN: "${RED_TOKEN}"
    volumes:
      - type: volume
        source: discord-config
        target: /home/discord/.config/Red-DiscordBot
      - type: volume
        source: discord-data
        target: /home/discord/.local/share/Red-DiscordBot/data
    ports:
      - "8080:8080"

  shopify:
    container_name: shopify
    profiles:
      - shopify
    image: ghcr.io/yellow-corps/ibis-shopify:latest
    build:
      context: ./shopify
      dockerfile: ./Containerfile
    restart: unless-stopped
    environment:
      SHOPIFY_CLIENT_ID: "${SHOPIFY_CLIENT_ID}"
      SHOPIFY_CLIENT_SECRET: "${SHOPIFY_CLIENT_SECRET}"
    network_mode: "service:discord"

  ngrok:
    container_name: ngrok
    profiles:
      - shopify
    image: ngrok/ngrok:latest
    restart: unless-stopped
    environment:
      NGROK_AUTHTOKEN: "${NGROK_AUTHTOKEN}"
    command:
      - http
      - "--url=${NGROK_DOMAIN}"
      - "http://discord:8080"
    depends_on:
      - shopify

  exporter:
    container_name: exporter
    profiles:
      - exporter
    image: ghcr.io/yellow-corps/ibis-exporter:latest
    build:
      context: ./exporter
      dockerfile: ./Containerfile
    restart: unless-stopped
    environment:
      RED_TOKEN: "${RED_TOKEN}"
    network_mode: "service:discord"

volumes:
  discord-config:
  discord-data:
