FROM python:3.11-alpine

LABEL org.opencontainers.image.source=https://github.com/yellow-corps/ibis
LABEL org.opencontainers.image.description="ibis discord bot"
LABEL org.opencontainers.image.licenses=MIT

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt /root/requirements.txt

RUN apk add --no-cache python3 git py3-pip gcc python3-dev musl-dev linux-headers

RUN python -m pip install pip && \
  python -m pip install -r /root/requirements.txt

RUN apk del py3-pip gcc python3-dev musl-dev linux-headers

# disable startup version check DM - it's so annoying!!
RUN sed -i -e \
  's/await send_to_owners_with_prefix_replaced(bot, outdated_red_message)/pass/' \
  "$(pip show Red-DiscordBot | grep "Location:" | awk '{print $2}')/redbot/core/_events.py"

COPY config/config.json /root/.config/Red-DiscordBot/config.json
COPY local-share/data/ibis /root/.local/share/Red-DiscordBot/data/ibis
COPY submodules/Trusty-cogs/extendedmodlog/ /root/.local/share/Red-DiscordBot/data/ibis/cogs/CogManager/cogs/extendedmodlog/
COPY submodules/coffee-cogs/msgmover/ /root/.local/share/Red-DiscordBot/data/ibis/cogs/CogManager/cogs/msgmover/
COPY cogs/persistmessages/ /root/.local/share/Red-DiscordBot/data/ibis/cogs/CogManager/cogs/persistmessages/
COPY cogs/shopify/ /root/.local/share/Red-DiscordBot/data/ibis/cogs/CogManager/cogs/shopify/
COPY cogs/sostickets/ /root/.local/share/Red-DiscordBot/data/ibis/cogs/CogManager/cogs/sostickets/
COPY cogs/uniqueinvites/ /root/.local/share/Red-DiscordBot/data/ibis/cogs/CogManager/cogs/uniqueinvites/

CMD ["redbot", "ibis", "--rpc", "--team-developers-are-owners", "--mentionable", "--prefix", "[@]"]
