FROM python:3.11-alpine

ARG WITH_OTEL

LABEL \
  org.opencontainers.image.source=https://github.com/yellow-corps/ibis \
  org.opencontainers.image.description="ibis discord bot${WITH_OTEL:+ with otel}" \
  org.opencontainers.image.licenses=MIT

ENV \
  WITH_OTEL=$WITH_OTEL \
  PYTHONDONTWRITEBYTECODE=1 \
  PYTHONUNBUFFERED=1

RUN \
  addgroup -S discord && \
  adduser -S discord -G discord

ARG DUCKDB_BUILD_DEPENDENCIES="musl-dev linux-headers"
RUN \
  apk add --no-cache g++ $DUCKDB_BUILD_DEPENDENCIES && \
  python -m pip install --upgrade pip

USER discord  
WORKDIR /home/discord

COPY --chown=discord ./requirements/ ./requirements/
RUN \
  export REQUIREMENTS_FILE=$( [[ -n "$WITH_OTEL" ]] && echo "main-otel.txt" || echo "main.txt" ) && \
  export PATH="$PATH:/home/discord/.local/bin" && \
  python -m pip install --user -r "requirements/$REQUIREMENTS_FILE" && \
  python -m pip cache purge && \
  rm -rf ./requirements/

USER root
RUN apk del $DUCKDB_BUILD_DEPENDENCIES 
USER discord

COPY ./patches.sh .
RUN \
  ./patches.sh && \
  rm ./patches.sh

COPY --chown=discord ./config/config.json .config/Red-DiscordBot/config.json
COPY --chown=discord ./local-share/data/ibis .local/share/Red-DiscordBot/data/ibis
COPY --chown=discord ./submodules/Trusty-cogs/extendedmodlog/ .local/share/Red-DiscordBot/cogs/extendedmodlog/
COPY --chown=discord ./submodules/coffee-cogs/msgmover/ .local/share/Red-DiscordBot/cogs/msgmover/
COPY --chown=discord ./cogs/ .local/share/Red-DiscordBot/cogs/
COPY ./ibis/ /usr/local/lib/python3.11/site-packages/ibis/
COPY ./docker-entrypoint.sh .

RUN [[ -z "$WITH_OTEL" ]] || .local/bin/opentelemetry-bootstrap --action=install

ENTRYPOINT ["/bin/sh", "-c", "./docker-entrypoint.sh"]
