FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt /root/requirements.txt

RUN <<EOF

apt update
apt -y install python3 python3-dev python3-venv git openjdk-17-jre-headless build-essential

python -m pip install pip
python -m pip install -r /root/requirements.txt

EOF

COPY config/config.json /root/.config/Red-DiscordBot/config.json
COPY local-share/data/ibis /root/.local/share/Red-DiscordBot/data/ibis
COPY submodules/Trusty-cogs/extendedmodlog/ /root/.local/share/Red-DiscordBot/data/ibis/cogs/CogManager/cogs/extendedmodlog/
COPY submodules/coffee-cogs/msgmover/ /root/.local/share/Red-DiscordBot/data/ibis/cogs/CogManager/cogs/msgmover/
COPY cogs/shopify/ /root/.local/share/Red-DiscordBot/data/ibis/cogs/CogManager/cogs/shopify/

CMD ["redbot", "ibis", "--rpc", "--team-developers-are-owners", "--mentionable", "--prefix", "[@]"]
