FROM node:24-alpine AS builder

WORKDIR /builder

COPY package.json package-lock.json ./

RUN npm ci

COPY src/index.ts ./src/

RUN npm run build && npm install --omit dev

FROM node:24-alpine

ARG WITH_OTEL

LABEL \
  org.opencontainers.image.source=https://github.com/yellow-corps/ibis \
  org.opencontainers.image.description="ibis shopify webhook receiver${WITH_OTEL:+ with otel}" \
  org.opencontainers.image.licenses=MIT

ENV WITH_OTEL=$WITH_OTEL

RUN \
  addgroup -S shopify && \
  adduser -S shopify -G shopify

USER shopify
WORKDIR /home/shopify

COPY --from=builder /builder/target/index.mjs ./
COPY --from=builder /builder/node_modules ./node_modules
COPY ./docker-entrypoint.sh ./docker-entrypoint.sh

STOPSIGNAL SIGKILL
ENTRYPOINT ["/bin/sh", "-c", "./docker-entrypoint.sh"]
