---
name: Deploy Docker

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
        type: string

jobs:
  deploy-docker:
    strategy:
      matrix:
        container: [discord, exporter, shopify]

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Deploy ${{ matrix.container }} container
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=gha,scope=${{ matrix.container }}
          cache-to: type=gha,mode=max,scope=${{ matrix.container }}
          context: ${{ github.workspace }}/${{ matrix.container }}
          file: ${{ github.workspace }}/${{ matrix.container }}/Containerfile
          tags: |
            ghcr.io/yellow-corps/ibis-${{ matrix.container }}:latest
            ghcr.io/yellow-corps/ibis-${{ matrix.container }}:${{ inputs.version }}
